import 'package:flutter/material.dart';
import 'package:tasks/src/core/utils/app_colors.dart';
import 'package:tasks/src/core/utils/gaps.dart';

Column customTextFeild({
  controller,
  title,
  hint,
  icon,
  suffixIconColor,
  lines = 1,
  isTitileAviable = true,
  keyboardType,
  textInputAction,
  maxLength,
  inputFormatters,
  color,
  String? Function(String?)? validator,
  void Function(String?)? onChanged,
  obscureText = false,
  border,
  padding = const EdgeInsets.symmetric(vertical: 10.0, horizontal: 14.0),
  hintStyle,
  isFill = false,
  titleStyle,
  contentStyle,
  editable = true,
  suffixIcon,
  prefixIcon,
  prefixIconConstraints,
  errorBorder,
}) {
  return Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
      isTitileAviable ? Text(title, style: titleStyle) : const SizedBox(),
      isTitileAviable ? AppGaps.hGap6 : const SizedBox(),
      TextFormField(
        inputFormatters: inputFormatters,
        obscureText: obscureText,
        maxLength: maxLength,
        controller: controller,
        cursorColor: AppColors.primary,
        validator: validator,
        onChanged: onChanged,
        maxLines: lines,
        keyboardType: keyboardType,
        textInputAction: textInputAction,
        style: contentStyle,
        decoration: InputDecoration(
          enabled: editable,
          enabledBorder: border,
          disabledBorder: border,
          border: border,
          focusedBorder: border,
          errorBorder: errorBorder,
          contentPadding: padding,
          filled: isFill,
          fillColor: color,
          isDense: true,
          hintText: hint,
          hintStyle: hintStyle,
          suffixIcon: suffixIcon,
          suffixIconConstraints: BoxConstraints(minHeight: 24, minWidth: 34),
          prefixIcon: prefixIcon,
          prefixIconConstraints: prefixIconConstraints,
        ),
      ),
    ],
  );
}
